version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo:5.0.13
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./data/mongo:/data/db
    networks:
      gateway:

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
    networks:
      gateway:

networks:
  gateway:
    external: true